import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { IoIosEasel } from "react-icons/io";
import { AiTwotoneAppstore } from "react-icons/ai";
import { HiOutlineBookmark } from "react-icons/hi2";
import { MdLocalMovies } from "react-icons/md";
import { AiFillCalendar } from "react-icons/ai";
// import path from "path";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uz">
      <body className='container bg-[#10141E] min-h-[100vh]'>
        <div className="container py-[32px] flex">
          <div className="left_sidebar flex flex-col bg-[#161D2F] w-16 h-[800px] rounded-lg pt-[25px] mb-4 gap-4">
            <span style={{ color: '#FC4747', fontSize: '32px', margin: '0 auto', marginBottom: '30px' }}><AiFillCalendar /></span>
            {/* <img src={path} alt="" /> */}
            <Link style={{ marginBottom: '20px', color: '#5A698F', fontSize: '20px', margin: '0 auto' }} href={'/'}><AiTwotoneAppstore /></Link>
            <Link style={{ marginBottom: '20px', color: '#5A698F', fontSize: '20px', margin: '0 auto' }} href={'/movies'}><MdLocalMovies /></Link>
            <Link style={{ marginBottom: '20px', color: '#5A698F', fontSize: '20px', margin: '0 auto' }} href={'/products'}><IoIosEasel /></Link>
            <Link style={{ color: '#5A698F', fontSize: '20px', margin: '0 auto' }} href={'/bockmard'}><HiOutlineBookmark /></Link>
          </div>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
